apiVersion: v1
kind: Service
metadata:
  name: artguard-service
spec:
  type: NodePort
  selector:
    app: artguard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30225  

